### PR TITLE
Refactor repository structure

### PR DESCRIPTION
**Pull request by josemigallas**
### Refactoring the structure of push-network-proxies

JIRA: https://issues.jboss.org/browse/AGPUSH-2127
Aerogear-dev thread: http://lists.jboss.org/pipermail/aerogear-dev/2017-June/012880.html

We have been recently using Wiremock implementation of FCM proxy as well as the previously existing APNs java mock. Since it makes no sense creating a new repo only for the fcm-wiremock, all the current and future implementations will be stored here, thanks to the new structure.

Each proxy/mock will have its own folder with a Dockerfile and a Readme inside (if applies). Also, Openshift templates can be written and stored under **openshift-templates** folder.

NOTE: the current implementation of the proxies is a Maven project that offers GCM and APNs mocks. However, the project must be run twice to provide both at the same time. Eventually this project should be decoupled in two: one only for APNs under **apns-java** and other only for GCM under **gcm-java**.

### CODE REVIEW

**Comment by secondsun** [comment]
What are the testing instructions?

I can follow the readmes, but there is some setup on UPS that probably needs to be done to exercise them right?

**Comment by josemigallas** [comment]
@secondsun That's a tricky question. The proxies shouldn't really need UPS to be tested. For fcm-wiremock for example, the only steps are to run the docker image and try to reach it via HTTP, with curl for example.
APNS should not need any verification since I just moved everything to apns-java. What I wonder is what should I do with Travis.
The most complex thing would be the template. I think loading it into Openshift and trying to reach both enfpoints (fcm at 3000 and anps at 16002) should be enough.
I would appreciate some comments about overall structure and Readmes, I probably missed something.

**Comment by secondsun** [comment]
So one thing that I notice is that you've added a README.md but the project has a README.adoc already, those probably need to be merged.  Still looking but figured that I would call that out now .

**Comment by josemigallas** [comment]
@secondsun the original Readme was only about apns/gcm java proxy, hence this one is inside that folder. On the other hand the new Readme is about a general description of the new structure (repo for many projects). Is this what you meant?

**Review by matskiv — APPROVED** [review]
LGTM

**Pull request merged**
